feat: 버튼 컴포넌트 구현
prgrms-fe-devcourse/FEDC2_LUVOOK_Jieun pull request #7
Opened 2022-06-09 15:46 UTC by dar-jeeling

### ✅ 이슈 번호
#3 
### 작업 내용(자세히)
![buttonstyle](https://user-images.githubusercontent.com/74234333/172887988-d562a68c-5e5e-4c80-bfb0-894b3a03bba3.gif)
- 기본적인 버튼 컴포넌트를 구현하였습니다.
- `buttonStyle`과 `onClick`을 props로 받으며, 이 부분은 사용자가 커스터마이징 할 수 있습니다.
→ style의 경우, 기본적으로 재사용되는 부분은 class로 사용하도록 하였습니다. 
`Button.css`에 해당 부분에 대한 논의가 필요할 것 같습니다.
- 커스텀 스타일의 경우 `props`의 `buttonStyle`에 css 형식으로 객체를 넣으시거나, 혹은 inline으로 style={ {이 안에 코드 작성} }으로 사용할 수 있습니다.

이미지가 없는 부분이나 자세한 코드 구현은 스토리북에서 확인하실 수 있습니다.

### 구현 날짜
220610

### 어려웠던 점
- 재사용가능한 스타일의 `width`, `height`, `color`와 같은 속성은 Figma 의 구현대로 임의로 사용하였으나,
이런 경우, constants에 **style에 관한 상수들(상수정의, 클래스 이름)**을 우선적으로 만드는 것을 논의해야할 것 같습니다.
(프로젝트에 사용되는 버튼의 종류가 제한되어 있기 때문에)

- 또한, 스타일을 위하여 css 파일로 클래스를 정의해서 사용하였으나, 위와 같이 pure css의 문법으로는 불편한 점이 많아서 프로젝트에 scss 를 도입하는 의견을 내고 싶습니다.

2022-06-09 17:04 UTC, ryong9rrr requested changes
Base Button인데 Base의 범위를 넘어버린 것 같아요. Base Button은 정말 최소한의 css만 가지고 있고 사용하는 쪽에서 규격화된 버튼으로 다시 만드는 방향이 좋을 것 같습니다. 

예를 들어 갈색 버튼을 만든다면
```js
const 갈색 버튼 = styled(BaseButton)`...`
```
이런 식으로 하는게 나아 보이는데... 잘 모르겠네요 ㅜㅜ
일단 보류하고 멘토님 조언을 한번 참고해보는게 좋을 것 같습니다.

2022-06-09 17:27 UTC, dar-jeeling commented
네 바로 수정할게요

2022-06-09 19:31 UTC, taewook1 approved these changes
다은님 고생 많으셨습니다. 저한테 딱히 문제라고 보이는 점은 없으나 css 파일을 이미 따로 두셨기에 통일성을 위해 이 부분은 다른 팀원분들과 상의를 해서 merge를 결정을 해야 하지 않을까 싶습니다.

2022-06-10 06:18 UTC, dar-jeeling commented on src/components/base/Button/Button.css
> +}
네 저도 그런 생각이드네요!
컴포넌트의 응집력을 위하여 스타일 관련 내용 지우겠습니다!
논의해주셔서 감사합니다.

2022-06-10 06:48 UTC, ryong9rrr approved these changes
고생하셨습니다!! 👍👍👍

2022-06-10 09:07 UTC, sukyeongh commented
LGTM! 머지해도 될 것 같아용

2022-06-10 09:15 UTC, merged