feat: select 컴포넌트 생성
prgrms-fe-devcourse/FEDC2_LUVOOK_Jieun pull request #9
Opened 2022-06-09 15:58 UTC by taewook1

### ✅ 이슈 번호
#2 feat: Select 컴포넌트 생성
### 작업 내용(자세히)
기본
![image](https://user-images.githubusercontent.com/67237560/172890790-56ac80cb-925a-4775-89e2-803e6120f457.png)
클릭 시
![image](https://user-images.githubusercontent.com/67237560/172891314-29500263-513a-4c48-8204-0d748e8b7c1c.png)
선택 시
![image](https://user-images.githubusercontent.com/67237560/172891433-33ceeb69-19ef-4cd2-9fca-929d4f108d0e.png)

1. Select 컴포넌트 추가
 - Label은 카테고리
 - Placeholder는 유도 문구로 넣으면 될거라 생각됩니다.
 - 색상은 피그마에 있는 시그니처 색으로 border와 label 색상을 지정해놨습니다.
 - Select 안에 텍스트는 기본 검은색으로 하는게 좋을 것 같아 따로 지정하지 않았습니다.

### 구현 날짜
2022-06-10

2022-06-09 17:17 UTC, ryong9rrr approved these changes
고생하셨습니다! PropTypes만 추가해주시면 좋을 것 같아요 😆

2022-06-09 17:17 UTC, ryong9rrr commented on src/components/base/Select/index.js
> +
PropTypes 추가하면 좋을 것 같습니다.
```js
Select.propTypes = {
  data: PropTypes.arrayOf(
    PropTypes.oneOfType([
      PropTypes.string,
      PropTypes.shape({
        label: PropTypes.string,
        value: PropTypes.string,
      }),
    ])
  ),
  label: PropTypes.string,
  placeholder: PropTypes.string,
  block: PropTypes.bool,
  invalid: PropTypes.bool,
  required: PropTypes.bool,
  disabled: PropTypes.bool,
  wrapperProps: PropTypes.object,
};
```

2022-06-09 17:23 UTC, dar-jeeling requested changes
안녕하세요 태욱님!
`src/components/base/Select/index.js`에 있는 오타 하나만 고치면 문제 없다고 생각합니다!
구현하시느라 수고 많으셨습니다!!

2022-06-09 17:23 UTC, dar-jeeling commented on src/components/base/Select/index.js
> +  display: block;
Label의 경우, 기본 `display`를 `none`으로 해도 괜찮을 것 같습니다. 
웹 접근성 이슈가 있으니 태그는 살려두는게 좋을 것 같아요.

2022-06-09 17:29 UTC, taewook1 commented on src/components/base/Select/index.js
> +  display: block;
네

2022-06-10 07:20 UTC, ryong9rrr approved these changes
이것만 수정해주시면 될 것 같습니다!

2022-06-10 07:20 UTC, ryong9rrr commented on src/components/base/Select/index.js
> +import propTypes from 'prop-types'
import PropTypes from 'prop-types' 입니다!!

2022-06-10 07:38 UTC, taewook1 commented on src/components/base/Select/index.js
> +import propTypes from 'prop-types'
띠용~

2022-06-10 08:00 UTC, sukyeongh approved these changes
확인 완료! LGTM

2022-06-10 08:00 UTC, merged